on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Java 17 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle einrichten
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: APK bauen
        run: gradle :app:assembleDebug --no-daemon

      - name: APK bereitstellen
        uses: actions/upload-artifact@v4
        with:
          name: TrackMan-Capture-APK
          path: app/build/outputs/apk/debug/app-debug.apk
